version: '3.8'
services:
  backendapp:
    container_name: app
    image: "backend-app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend-net
    depends_on:
      - postgresql
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/db
       - SPRING_DATASOURCE_USERNAME=postgres
       - SPRING_DATASOURCE_PASSWORD=password
       - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresql:
    container_name: postgresql
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      backend-net:

networks:
  backend-net:
    driver: bridge

